name: share_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  cpf_cnpj_validator: ^2.0.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  validators: ^3.0.0
  google_sign_in: ^6.1.0
  firebase_messaging: ^14.5.0
  location: ^4.4.0
  workmanager: ^0.5.1
  shared_preferences: ^2.1.0
  flutter_dotenv: ^5.0.2
  retrofit: ^4.0.1
  dio: ^5.1.0
  json_annotation: ^4.8.1
  retrofit_generator: ^6.0.0+3
  get: ^4.6.5
  http: ^0.13.6
  flutter_local_notifications: ^14.1.0
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  uuid: ^3.0.7
  provider: ^6.0.1
  flutter_plugin_tools: ^0.13.4+3

dev_dependencies:
  json_serializable: ^6.6.2
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png
