// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjeGkJbbcr-gTZ-1zOOuxuUILqGwHJiuo',
    appId: '1:1014358974664:android:92efcf45fe35276291c5fd',
    messagingSenderId: '1014358974664',
    projectId: 'share-app-mobile',
    databaseURL: 'https://share-app-mobile-default-rtdb.firebaseio.com',
    storageBucket: 'share-app-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXSWizeM_iFYpdJe8mXGDTvaO0c7kAGnU',
    appId: '1:1014358974664:ios:64d351f3e5e33c1b91c5fd',
    messagingSenderId: '1014358974664',
    projectId: 'share-app-mobile',
    databaseURL: 'https://share-app-mobile-default-rtdb.firebaseio.com',
    storageBucket: 'share-app-mobile.appspot.com',
    iosClientId: '1014358974664-rrqb66bktqbjaqs4qtctnrfn9vupja9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareApp',
  );
}
