// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    // switch (defaultTargetPlatform) {
    //   case TargetPlatform.android:
    //     return android;
    //   case TargetPlatform.iOS:
    //     return ios;
    //   case TargetPlatform.macOS:
    //     throw UnsupportedError(
    //       'DefaultFirebaseOptions have not been configured for macos - '
    //       'you can reconfigure this by running the FlutterFire CLI again.',
    //     );
    // }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyA8KrHHSdNTNODPnENW5iIooPlgSh-Eo30',
  //   appId: '1:233998926519:android:fd093ecd8d83f71357c332',
  //   messagingSenderId: '233998926519',
  //   projectId: 'pipa-293216',
  //   storageBucket: 'pipa-293216.appspot.com',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDjeGkJbbcr-gTZ-1zOOuxuUILqGwHJiuo',
  //   appId: '1:1014358974664:ios:5b422653bf9aadbb91c5fd',
  //   messagingSenderId: '233998926519',
  //   projectId: 'pipa-293216',
  //   storageBucket: 'pipa-293216.appspot.com',
  //   iosClientId:
  //       '233998926519-tdaf3a9e874s4ai660luoaqcll8us3vm.apps.googleusercontent.com',
  //   iosBundleId: 'br.com.azos.app.clientebroker',
  // );
}
